### ISSUE TITLE
Typo in the solution of Exercise 1.6?

### ISSUE THREAD

**Issue by egorgladin** [PerformanceEstimation/Learning-Performance-Estimation#1]
It seems that there is a typo in the solution of Exercise 1.6. Specifically, when you rewrite the objective in terms of h_k (see [this line](https://github.com/PerformanceEstimation/Learning-Performance-Estimation/blob/d1ed0b46da88c71887181d15dc711eed5de1fe7b/Course.tex#L233C26-L233C67)), it should be `G_{1,1} + h_k^2 G_{2,2} / L^2 - 2h_k G_{1,2} / L` (division instead of multiplication).

**Comment by bgoujaud** [comment]
Thank you for your careful reading!
A fix is now provided in the associated PR.

**Comment by AdrienTaylor** [comment]
Thanks to both of you!
